#!/usr/bin/env php
<?php
/**
* eZ Upgrade
*
* @copyright //autogentag//
* @license //autogentag//
* @version //autogentag//
*/

include_once( "classes/ezupgrade.php" );
$upgrade = new eZUpgrade;
$account = $argv[1];

// if no account name is specified
if ( $account == '' )
{
	$upgrade->describeUsage();
	exit();
}

$blockName = 'Account_'.$account;

$toVersion		= $upgrade->cfg->getSetting( 'account', $blockName, 'ToVersion');
$basePath		= $upgrade->cfg->getSetting( 'account', $blockName, 'BasePath');
$instLoc		= $upgrade->cfg->getSetting( 'account', $blockName, 'ExistingInstallationLocation');
$siteAccessList	= $upgrade->cfg->getSetting( 'account', $blockName, 'SiteaccessList' );

// Ensure trailing slash on valid paths
if ( is_dir( $basePath ) )
{
	$basePath = realpath( $basePath ) . DIRECTORY_SEPARATOR;
}
else
{
	printf( $basePath . " does not exist. Check BasePath in account.ini \n" );
	exit();
}

if ( $instLoc != 'remote' )
{
	if ( is_dir( $instLoc ) )
	{
		$instLoc = realpath( $instLoc ) . DIRECTORY_SEPARATOR;
	}
	else
	{
		printf( $instLoc . " does not exist. Check ExistingInstallationLocation in account.ini \n" );
		exit();
	}
}

$data = array(	'account_name'			=> $account,
				'upgrade_to_version' 	=> $toVersion, 
				'upgrade_base_path'		=> $basePath, 
				'existing_install'		=> $instLoc,
				'siteaccess_list'		=> $siteAccessList );

if ( $upgrade->checkParamsBeforeRunning( $data ) )
{
	$upgrade->setUpgradeData($data);
	$upgrade->run();
}
else
{
	echo 'error';
}

?>
