#!/usr/bin/php
<?php

include_once( "classes/ezupgrade.php" );
$upgrade = new eZUpgrade;
$account 	 = $argv[1];

if ( $account == '' )
{
	$upgrade->describeUsage();
	exit();
}

$blockName = 'Account_'.$account;

$toVersion		= $upgrade->cfg->getSetting( 'account', $blockName, 'ToVersion');
$basePath		= $upgrade->cfg->getSetting( 'account', $blockName, 'BasePath');
$oldFolder		= $upgrade->cfg->getSetting( 'account', $blockName, 'OldInstallFolderName');
$newFolder		= $upgrade->cfg->getSetting( 'account', $blockName, 'NewInstallFolderName');

$data = array(	'account_name'			=> $account,
				'upgrade_to_version' 	=> $toVersion, 
				'upgrade_base_path'		=> $basePath, 
				'old_folder_name'		=> $oldFolder,
				'new_folder_name'		=> $newFolder );

if ( $upgrade->checkParamsBeforeRunning( $data ) )
{
	$upgrade->setUpgradeData($data);
	$upgrade->run();
}
else
{
	echo 'error';
}


?>